docs(sistent): fix Universal Filter name for sorting and SSR
Add missing frontmatter name field required by
src/pages/projects/sistent/components/index.js:19 and
src/sections/Projects/Sistent/components/index.js:30
(a.name.localeCompare(b.name)) which caused
TypeError: Cannot read properties of null (reading 'localeCompare')
on /projects/sistent/components. Align title/description with
passing duplicate #7990 (Ayush-1812).

Fixes #7984
Signed-off-by: Kumar Nirupam <kumar.nirupam24@gmail.com>